SELECT UL.EQUIPMENT_MARK, lpad(UL.EQUIPMENT_NUMBER , 6, '0') as EQUIPMENT_NUMBER, UL.EQUIPMENT_IDENTIFICATION,UL.STATUS_CODE, UL.BUILT_DATE,
       UL.STATUS_CHANGE_REASON, UL.STATUS_CHANGE_DATE, UL.END_OF_SERVICE_DATE, UL.PRIOR_EQUIPMENT_ID,
       UL.EQUIPMENT_ADD_DATE, UL.CAR_TYPE, UL.REGISTRATION_REASON, UL.REPORTING_MARK, UL.LESSEE,
       ES.START_DATE, ES.STOP_DATE,(C.CONTRACT_NAME || '  ' || C.CONTRACT_NUMBER )AS CONTRACT, '' as discrepancyReason
From UMLER UL
JOIN EQUIPMENTS ES
    ON (UL.EQUIPMENT_MARK = ES.EQUIPMENT_INITIAL
    AND lpad(UL.EQUIPMENT_NUMBER , 6, '0') = ES.EQUIPMENT_NUMBER)
LEFT JOIN EQUIPMENT_CONTRACT EC
    ON (EC.EQUIPMENT_ID = ES.EQUIPMENT_ID
    AND trunc(sysDate) BETWEEN EC.IN_CONTRACT_START_DATE and EC.IN_CONTRACT_STOP_DATE)
LEFT JOIN CONTRACT C
    ON C.CONTRACT_ID = EC.CONTRACT_ID
WHERE UL.EQUIPMENT_MARK =:equipmentMark

UNION

SELECT UL.EQUIPMENT_MARK, lpad(UL.EQUIPMENT_NUMBER , 6, '0') as EQUIPMENT_NUMBER, UL.EQUIPMENT_IDENTIFICATION,UL.STATUS_CODE, UL.BUILT_DATE,
       UL.STATUS_CHANGE_REASON, UL.STATUS_CHANGE_DATE, UL.END_OF_SERVICE_DATE, UL.PRIOR_EQUIPMENT_ID,
       UL.EQUIPMENT_ADD_DATE, UL.CAR_TYPE, UL.REGISTRATION_REASON, UL.REPORTING_MARK, UL.LESSEE,
       ES.START_DATE, ES.STOP_DATE,(C.CONTRACT_NAME || '  ' || C.CONTRACT_NUMBER )AS CONTRACT,
       CASE
         WHEN  ES.EQUIPMENT_INITIAL is null THEN
            CASE
             WHEN (trunc(sysDate) <=  UL.EXPIRATION_DATE) AND (trunc(sysDate) >= UL.EFFECTIVE_DATE) THEN 'Equipment is active in UMLER but not in GE Fleet'
             WHEN (trunc(sysDate) >  UL.EXPIRATION_DATE) THEN 'Equipment is inactive in UMLER but not in GE fleet'
             WHEN (trunc(sysDate) <  UL.EFFECTIVE_DATE) THEN 'Equipment is pre-registered in UMLER but not in  GE fleet'
             END
       ELSE ''
       END AS discrepancyReason
From UMLER UL
LEFT JOIN EQUIPMENTS ES
    ON (UL.EQUIPMENT_MARK = ES.EQUIPMENT_INITIAL
    AND lpad(UL.EQUIPMENT_NUMBER , 6, '0') = ES.EQUIPMENT_NUMBER)
LEFT JOIN EQUIPMENT_CONTRACT EC
    ON (EC.EQUIPMENT_ID = ES.EQUIPMENT_ID
    AND trunc(sysDate) BETWEEN EC.IN_CONTRACT_START_DATE and EC.IN_CONTRACT_STOP_DATE)
LEFT JOIN CONTRACT C
    ON C.CONTRACT_ID = EC.CONTRACT_ID
WHERE UL.EQUIPMENT_MARK =:equipmentMark

UNION

SELECT ES.EQUIPMENT_INITIAL, lpad(ES.EQUIPMENT_NUMBER , 6, '0') as EQUIPMENT_NUMBER, UL.EQUIPMENT_IDENTIFICATION,UL.STATUS_CODE, UL.BUILT_DATE,
       UL.STATUS_CHANGE_REASON, UL.STATUS_CHANGE_DATE, UL.END_OF_SERVICE_DATE, UL.PRIOR_EQUIPMENT_ID,
       UL.EQUIPMENT_ADD_DATE, UL.CAR_TYPE, UL.REGISTRATION_REASON, UL.REPORTING_MARK, UL.LESSEE,
       ES.START_DATE, ES.STOP_DATE,(C.CONTRACT_NAME || '  ' || C.CONTRACT_NUMBER )AS CONTRACT,
       CASE UL.EQUIPMENT_MARK
         WHEN ES.EQUIPMENT_INITIAL THEN ''
       ELSE 'Active in GE Fleet Not in UMLER'
       END AS discrepancyReason
From EQUIPMENTS ES
LEFT JOIN  UMLER UL
    ON (UL.EQUIPMENT_MARK = ES.EQUIPMENT_INITIAL
    AND lpad(UL.EQUIPMENT_NUMBER , 6, '0') = ES.EQUIPMENT_NUMBER)
LEFT JOIN EQUIPMENT_CONTRACT EC
    ON (EC.EQUIPMENT_ID = ES.EQUIPMENT_ID
    AND trunc(sysDate) BETWEEN EC.IN_CONTRACT_START_DATE and EC.IN_CONTRACT_STOP_DATE)
LEFT JOIN CONTRACT C
    ON C.CONTRACT_ID = EC.CONTRACT_ID

WHERE ES.EQUIPMENT_INITIAL =:equipmentMark;